name: Docker Images CI

on:
  schedule:
  - cron: "33 9 * * 1-5"
  workflow_dispatch:


jobs:
  build-docker-r1Obr-sim:
    runs-on: ubuntu-latest
    steps:
    - name: Info
      run: |
       echo "Event type: ${{github.event_name}}"
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
    - name: Change docker to experimental mode
      run: |
       sudo rm -rf /etc/docker/daemon.json
       echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
    - name: Restart docker daemon
      run: sudo systemctl restart docker
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: |
        echo "Free space:"
        df -h
    - name: Build the R1 Object Retrieval Sim Docker image
      working-directory: docker/docker_r1ObjectRetrievalSim/
      run: sudo docker build --build-arg ros_distro="humble" -t "colombraf/r1images:r1ObjectRetrievalSim" .
    - name: Push R1 Object Retrieval Sim Docker image
      run: docker push colombraf/r1images:r1ObjectRetrievalSim

  build-docker-r1Obr:
    runs-on: ubuntu-latest
    steps:
    - name: Info
      run: |
       echo "Event type: ${{github.event_name}}"
    - name: Change docker to experimental mode
      run: |
       sudo rm -rf /etc/docker/daemon.json
       echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
    - name: Restart docker daemon
      run: sudo systemctl restart docker
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the R1 Object Retrieval Docker image
      working-directory: docker/docker_r1ObjectRetrieval/
      run: sudo docker build --build-arg ros_distro="humble" -t "colombraf/r1images:r1ObjectRetrieval" .
    - name: Push R1 Object Retrieval Docker image
      run: docker push colombraf/r1images:r1ObjectRetrieval
